# Generated by Django 5.1.15 on 2026-05-12 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modulebackupconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(db_index=True, help_text='Slug for modulen som lagde varselet.', max_length=64, verbose_name='Modul')),
                ('kind', models.CharField(help_text='Maskinell identifikator for varseltypen (brukes til filter og dedup).', max_length=64, verbose_name='Varseltype')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Advarsel'), ('critical', 'Kritisk')], default='info', help_text='Alvorlighetsgrad. Reservert for fremtidige UI-features (badge-farge, lyd, push). Per Fase 5 vises alle likt.', max_length=16, verbose_name='Nivå')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Melding')),
                ('url', models.CharField(blank=True, default='', help_text='Relativ URL som brukeren sendes til ved klikk.', max_length=500, verbose_name='Lenke')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lest')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Opprettet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Mottaker')),
            ],
            options={
                'verbose_name': 'Varsel',
                'verbose_name_plural': 'Varsler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_notif_user_read_idx'), models.Index(fields=['user', 'module_slug', '-created_at'], name='core_notif_user_module_idx')],
            },
        ),
    ]
