# Generated by Django 5.1.15 on 2026-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Settes til timezone.now() når brukeren markerer varselet som lest.', null=True, verbose_name='Lest tidspunkt'),
        ),
    ]
