# Generated by Django 5.2.17 on 2026-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_arkiv_backup_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vakt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        help_text="Fritekst, satt ved vaktstart: «Landsskytterstevnet 2026». Unikt — to vakter med samme navn lar seg ikke skille i statistikken. Trengs navnet igjen, legg på en dato.",
                        max_length=255,
                        unique=True,
                        verbose_name="Vaktnavn",
                    ),
                ),
                ("year", models.IntegerField(db_index=True, verbose_name="År")),
                ("startet", models.DateTimeField(verbose_name="Startet")),
                (
                    "avsluttet",
                    models.DateTimeField(
                        blank=True,
                        help_text="Settes av «Avslutt vakt». En avsluttet vakt kan gjenåpnes fram til arkivet er kollapset — etter det finnes ikke radnivået lenger.",
                        null=True,
                        verbose_name="Avsluttet",
                    ),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Vakt",
                "verbose_name_plural": "Vakter",
                "ordering": ["-startet"],
            },
        ),
    ]
