# Generated by Django 5.2.17 on 2026-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_vakt"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffsiteKopi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_filnavn",
                    models.CharField(max_length=255, verbose_name="Backup-fil"),
                ),
                (
                    "module_slug",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Modul"
                    ),
                ),
                (
                    "objektnavn",
                    models.CharField(max_length=300, verbose_name="Objekt i bucketen"),
                ),
                (
                    "bytes",
                    models.BigIntegerField(default=0, verbose_name="Bytes (kryptert)"),
                ),
                (
                    "sendt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lastet opp"
                    ),
                ),
                ("feil", models.TextField(blank=True, default="", verbose_name="Feil")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Forsøkt"),
                ),
            ],
            options={
                "verbose_name": "Offsite-kopi",
                "verbose_name_plural": "Offsite-kopier",
                "ordering": ["-created_at"],
            },
        ),
    ]
