# Generated by Django 5.2.17 on 2026-09-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_modulesettings_backup_enabled_slett_kolonnen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaktStatistikk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vakt_navn",
                    models.CharField(max_length=255, verbose_name="Vaktnavn"),
                ),
                (
                    "slug",
                    models.CharField(max_length=64, verbose_name="Statistikkilde"),
                ),
                (
                    "versjon",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Formversjon"
                    ),
                ),
                ("data", models.JSONField(verbose_name="Tallene")),
                (
                    "frosset_at",
                    models.DateTimeField(db_index=True, verbose_name="Frosset"),
                ),
                (
                    "frosset_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Frosset av (navn)",
                    ),
                ),
                (
                    "frosset_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Frosset av",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statistikk",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frosset vaktstatistikk",
                "verbose_name_plural": "Frosset vaktstatistikk",
                "ordering": ["-frosset_at", "slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vakt", "slug", "frosset_at"),
                        name="vaktstatistikk_en_per_fane_per_avslutning",
                    )
                ],
            },
        ),
    ]
