# Generated by Django 5.2.17 on 2026-09-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_vaktstatistikk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backup",
            name="kind",
            field=models.CharField(
                choices=[
                    ("auto", "Automatisk"),
                    ("manual", "Manuell"),
                    ("pre_restore", "Før gjenoppretting"),
                    ("pre_reset", "Før nullstilling av år"),
                    ("pre_slett", "Før sletting av vakt"),
                ],
                max_length=20,
            ),
        ),
    ]
