# Generated by Django 5.2.14 on 2026-08-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_module_permission_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Aktiv sesjonsnøkkel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
