# Generated by Django 5.2.14 on 2026-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='er_delt_konto',
            field=models.BooleanField(default=False, help_text='Ikke-personlig konto, f.eks. en bil. Utelukkes fra selvbetjent passord-reset.', verbose_name='Delt konto'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullt_navn',
            field=models.CharField(blank=True, default='', help_text='Valgfritt. Vises til admin for å kjenne igjen brukeren.', max_length=150, verbose_name='Fullt navn'),
        ),
    ]
