# Generated by Django 5.2.17 on 2026-08-28 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_er_delt_konto_customuser_fullt_navn"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulTilgang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "modul_slug",
                    models.CharField(
                        help_text="Matcher Module.slug i core.modules.",
                        max_length=64,
                        verbose_name="Modul",
                    ),
                ),
                (
                    "nivaa",
                    models.CharField(
                        choices=[
                            ("les", "Lese"),
                            ("skriv_handling", "Skrive: handling"),
                            ("skriv_full", "Skrive: full"),
                        ],
                        max_length=20,
                        verbose_name="Nivå",
                    ),
                ),
                (
                    "bruker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modultilganger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modultilgang",
                "verbose_name_plural": "Modultilganger",
                "ordering": ["bruker__username", "modul_slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bruker", "modul_slug"),
                        name="unik_modultilgang_per_bruker",
                    )
                ],
            },
        ),
    ]
