# Generated by Django 5.2.17 on 2026-09-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_legg_til_les_alle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Innlogging"),
                    ("passord_ok", "Passord riktig, MFA gjenstår"),
                    ("mfa_setup_completed", "MFA-oppsett fullført"),
                    ("mfa_verify_success", "MFA-verifisering vellykket"),
                    ("mfa_verify_failed", "MFA-verifisering feilet"),
                    ("mfa_backup_used", "MFA backup-kode brukt"),
                    ("mfa_trust_cookie_used", "MFA trust-cookie brukt"),
                    ("mfa_reset_by_admin", "MFA nullstilt av admin"),
                ],
                default="login",
                max_length=30,
                verbose_name="Hendelsestype",
            ),
        ),
    ]
