# Generated by Django 5.2 on 2026-09-17 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Innspill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("bug", "Bug"), ("onske", "Ønske")],
                        db_index=True,
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                (
                    "tittel",
                    models.CharField(
                        help_text="Én setning. Det du ville sagt i chatten.",
                        max_length=200,
                        verbose_name="Tittel",
                    ),
                ),
                (
                    "beskrivelse",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Valgfritt. Hva du gjorde, hva du forventet, hva som skjedde.",
                        verbose_name="Beskrivelse",
                    ),
                ),
                (
                    "modul_slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Gjelder modul",
                    ),
                ),
                (
                    "opprettet_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Meldt inn av (navn)",
                    ),
                ),
                (
                    "opprettet_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Meldt inn"),
                ),
                (
                    "endret_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sist endret"),
                ),
                (
                    "lost",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Løst"
                    ),
                ),
                (
                    "lost_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Løst av (navn)",
                    ),
                ),
                (
                    "lost_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Løst når"
                    ),
                ),
                (
                    "lost_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlog_lost",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Løst av",
                    ),
                ),
                (
                    "opprettet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlog_innspill",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Meldt inn av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Innspill",
                "verbose_name_plural": "Innspill",
                "ordering": ["-opprettet_at", "-pk"],
            },
        ),
    ]
