# Generated by Django 5.2 on 2026-09-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backlog", "0004_innspill_type_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kommentar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tekst", models.TextField(verbose_name="Kommentar")),
                (
                    "opprettet_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Skrevet av (navn)",
                    ),
                ),
                (
                    "opprettet_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skrevet"),
                ),
                (
                    "endret_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sist endret"),
                ),
                (
                    "innspill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kommentarer",
                        to="backlog.innspill",
                        verbose_name="Innspill",
                    ),
                ),
                (
                    "opprettet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlog_kommentarer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Skrevet av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kommentar",
                "verbose_name_plural": "Kommentarer",
                "ordering": ["opprettet_at", "pk"],
            },
        ),
    ]
