# Generated by Django 5.2.17 on 2026-09-26 14:00

import core.sortering
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backlog", "0005_kommentar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="innspilltype",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Innspilltype",
                "verbose_name_plural": "Innspilltyper",
            },
        ),
    ]
