# Generated by Django 5.2.17 on 2026-08-28 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lokasjon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Lokasjon"
                    ),
                ),
                (
                    "er_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktive lokasjoner skjules i nedtrekkslista, men beholdes på oppdragene som allerede bruker dem.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(
                        default=100,
                        help_text="Lavere kommer først i lista.",
                        verbose_name="Rekkefølge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokasjon",
                "verbose_name_plural": "Lokasjoner",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="Enhet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        help_text="Navnet som brukes på samband, f.eks. «Haugesund 56».",
                        max_length=64,
                        unique=True,
                        verbose_name="Enhetsnavn",
                    ),
                ),
                (
                    "er_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktive enheter kan ikke tildeles nye oppdrag.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Kontoen enheten logger inn med. Bør være en delt konto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enhet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Innlogget som",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enhet",
                "verbose_name_plural": "Enheter",
                "ordering": ["navn"],
            },
        ),
        migrations.CreateModel(
            name="Oppdrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                ("year", models.IntegerField(db_index=True, verbose_name="År")),
                (
                    "problemstilling",
                    models.CharField(max_length=255, verbose_name="Problemstilling"),
                ),
                (
                    "hastegrad",
                    models.CharField(
                        choices=[
                            ("Akutt", "Akutt"),
                            ("Haster", "Haster"),
                            ("Vanlig", "Vanlig"),
                        ],
                        max_length=16,
                        verbose_name="Hastegrad",
                    ),
                ),
                (
                    "fritekst",
                    models.TextField(blank=True, default="", verbose_name="Fritekst"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("venter", "Venter"),
                            ("rykker_ut", "Rykker ut"),
                            ("fremme", "Fremme"),
                            ("avreist", "Avreist"),
                            ("leverer", "Leverer"),
                            ("ledig", "Ledig"),
                        ],
                        db_index=True,
                        default="venter",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "enhet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oppdrag",
                        to="oppdrag.enhet",
                        verbose_name="Enhet",
                    ),
                ),
                (
                    "lokasjon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oppdrag",
                        to="oppdrag.lokasjon",
                        verbose_name="Lokasjon",
                    ),
                ),
                (
                    "opprettet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opprettede_oppdrag",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opprettet av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oppdrag",
                "verbose_name_plural": "Oppdrag",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enhetsbytte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "byttet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enhetsbytter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fra_enhet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="oppdrag.enhet",
                    ),
                ),
                (
                    "til_enhet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="oppdrag.enhet",
                    ),
                ),
                (
                    "oppdrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enhetsbytter",
                        to="oppdrag.oppdrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enhetsbytte",
                "verbose_name_plural": "Enhetsbytter",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Statusmelding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("venter", "Venter"),
                            ("rykker_ut", "Rykker ut"),
                            ("fremme", "Fremme"),
                            ("avreist", "Avreist"),
                            ("leverer", "Leverer"),
                            ("ledig", "Ledig"),
                        ],
                        max_length=16,
                    ),
                ),
                ("tidspunkt", models.DateTimeField(verbose_name="Tidspunkt")),
                (
                    "forsinket",
                    models.BooleanField(
                        default=False,
                        help_text="Klienten var frakoblet da knappen ble trykket.",
                        verbose_name="Meldt forsinket",
                    ),
                ),
                (
                    "automatisk",
                    models.BooleanField(
                        default=False,
                        help_text="Oppdraget ble avsluttet fordi enheten startet det neste.",
                        verbose_name="Satt automatisk",
                    ),
                ),
                (
                    "korrigerer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="korreksjoner",
                        to="oppdrag.statusmelding",
                        verbose_name="Korrigerer",
                    ),
                ),
                (
                    "meldt_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statusmeldinger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Meldt av",
                    ),
                ),
                (
                    "oppdrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statusmeldinger",
                        to="oppdrag.oppdrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statusmelding",
                "verbose_name_plural": "Statusmeldinger",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="oppdrag",
            index=models.Index(
                fields=["enhet", "status"], name="oppdrag_enhet_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oppdrag",
            index=models.Index(
                fields=["year", "status"], name="oppdrag_aar_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statusmelding",
            index=models.Index(
                fields=["oppdrag", "status"], name="statusmelding_opp_st_idx"
            ),
        ),
    ]
