# Generated by Django 5.2.17 on 2026-08-29 07:22

"""`pa_vakt` skilles fra `er_aktiv`.

Feltene svarer på to forskjellige spørsmål, og skillet er hvem som endrer dem
og hvor ofte. `er_aktiv` er oppsett — admin pensjonerer en bil. `pa_vakt` er
drift — 113 tar biler på og av gjennom vakta.

Ett felt for begge ville gjort «pensjonert» og «hjemme i kveld» til samme
tilstand, og den som skulle skru bilen på igjen ville ikke funnet den.

`default=True`: enheter som finnes i dag er i tjeneste. Å migrere dem til
«ikke på vakt» ville tatt dem av tavla ved neste deploy uten at noen bestemte
det.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enhet",
            name="pa_vakt",
            field=models.BooleanField(
                default=True,
                help_text="Enheter som ikke er på vakt kan ikke få nye oppdrag.",
                verbose_name="På vakt",
            ),
        ),
        migrations.AlterField(
            model_name="enhet",
            name="er_aktiv",
            field=models.BooleanField(
                default=True,
                help_text="Pensjonerte enheter skjules overalt. Settes av admin.",
                verbose_name="Aktiv",
            ),
        ),
    ]
