# Generated by Django 5.2.17 on 2026-08-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_vakt"),
        ("oppdrag", "0004_historikk_ikke_arkiv"),
    ]

    operations = [
        migrations.AddField(
            model_name="oppdrag",
            name="vakt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oppdrag",
                to="core.vakt",
                verbose_name="Vakt",
            ),
        ),
    ]
