# Generated by Django 5.2.17 on 2026-08-29 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_vakt"),
        ("oppdrag", "0007_vakt_er_fasit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OppdragArkiv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tittel", models.CharField(max_length=255, verbose_name="Tittel")),
                (
                    "vakt_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Navnet vakta hadde da arkivet ble laget. Frosset her fordi vakta kan bli omdøpt eller slettet, mens arkivet skal beskrive seg selv.",
                        max_length=255,
                        verbose_name="Vaktnavn (frosset)",
                    ),
                ),
                (
                    "antall_rader",
                    models.IntegerField(
                        default=0,
                        help_text="Antall arkiverte rader da arkivet ble laget.",
                        verbose_name="Antall rader",
                    ),
                ),
                (
                    "notat",
                    models.TextField(blank=True, default="", verbose_name="Notat"),
                ),
                (
                    "importert_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Arkivert"
                    ),
                ),
                (
                    "importert_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Frosset brukernavn. Settes ved arkivering og overlever sletting av brukerkontoen.",
                        max_length=150,
                        verbose_name="Arkivert av (navn)",
                    ),
                ),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                (
                    "kollapset_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Tidspunkt da radene ble slettet og erstattet av frosset aggregat. Tomt betyr at radnivået fortsatt finnes.",
                        null=True,
                        verbose_name="Kollapset",
                    ),
                ),
                (
                    "aggregat",
                    models.JSONField(
                        blank=True,
                        help_text="Ferdig beregnede tall lagret ved kollaps.",
                        null=True,
                        verbose_name="Frosset statistikk",
                    ),
                ),
                (
                    "aggregat_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sjekksum over det frosne aggregatet. Overtar integritetssjekken etter kollaps, siden «sha256» er beregnet over rader som ikke lenger finnes.",
                        max_length=64,
                        verbose_name="SHA-256 (aggregat)",
                    ),
                ),
                (
                    "importert_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_arkiver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Arkivert av",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_arkiver",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oppdragsarkiv",
                "verbose_name_plural": "Oppdragsarkiver",
                "ordering": ["-importert_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArkivertOppdrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oppdragsnummer", models.IntegerField(verbose_name="Oppdragsnummer")),
                (
                    "enhet_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Enhet (navn)",
                    ),
                ),
                (
                    "lokasjon_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Lokasjon (navn)",
                    ),
                ),
                (
                    "problemstilling",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Problemstilling",
                    ),
                ),
                (
                    "hastegrad",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="Hastegrad"
                    ),
                ),
                (
                    "sluttstatus",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Statusen oppdraget sto i da vakta ble arkivert.",
                        max_length=16,
                        verbose_name="Status ved arkivering",
                    ),
                ),
                ("opprettet_at", models.DateTimeField(verbose_name="Opprettet")),
                (
                    "rykker_ut_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rykker ut"
                    ),
                ),
                (
                    "fremme_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fremme"),
                ),
                (
                    "avreist_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Avreist"),
                ),
                (
                    "leverer_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Leverer"),
                ),
                (
                    "ledig_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ledig"),
                ),
                (
                    "automatiske_statuser",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Automatiske stemplinger"
                    ),
                ),
                (
                    "antall_forsinket",
                    models.IntegerField(
                        default=0,
                        help_text="Stemplinger sendt fra en enhet som var uten dekning.",
                        verbose_name="Forsinket meldte stemplinger",
                    ),
                ),
                (
                    "arkiv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oppdrag",
                        to="oppdrag.oppdragarkiv",
                        verbose_name="Arkiv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arkivert oppdrag",
                "verbose_name_plural": "Arkiverte oppdrag",
                "ordering": ["oppdragsnummer"],
                "unique_together": {("arkiv", "oppdragsnummer")},
            },
        ),
    ]
