# Generated by Django 5.2.17 on 2026-09-11 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0009_avreist_til_og_grovsortering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Oppdragsenhet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("venter", "Venter"),
                            ("rykker_ut", "Rykker ut"),
                            ("fremme", "Fremme"),
                            ("avreist", "Avreist"),
                            ("leverer", "Leverer"),
                            ("ledig", "Ledig"),
                        ],
                        db_index=True,
                        default="venter",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "varslet_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Varslet"
                    ),
                ),
                (
                    "rekkefolge",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Rekkefølge"
                    ),
                ),
                (
                    "enhet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oppdragsenheter",
                        to="oppdrag.enhet",
                        verbose_name="Enhet",
                    ),
                ),
                (
                    "oppdrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enheter",
                        to="oppdrag.oppdrag",
                        verbose_name="Oppdrag",
                    ),
                ),
                (
                    "varslet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="varslede_enheter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Varslet av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oppdragsenhet",
                "verbose_name_plural": "Oppdragsenheter",
                "ordering": ["rekkefolge", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="statusmelding",
            name="oppdragsenhet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statusmeldinger",
                to="oppdrag.oppdragsenhet",
                verbose_name="Enhet på oppdraget",
            ),
        ),
        migrations.AddIndex(
            model_name="oppdragsenhet",
            index=models.Index(
                fields=["enhet", "status"], name="oppdragsenhet_enh_st_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="oppdragsenhet",
            constraint=models.UniqueConstraint(
                fields=("oppdrag", "enhet"), name="unik_enhet_per_oppdrag"
            ),
        ),
    ]
