# Generated by Django 5.2.17 on 2026-09-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0011_fyll_oppdragsenhet"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusmelding",
            name="manuell",
            field=models.BooleanField(
                default=False,
                help_text="Ført av sentralbordet, ikke stemplet av enheten.",
                verbose_name="Ført manuelt",
            ),
        ),
    ]
