# Generated by Django 5.2.17 on 2026-09-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0012_statusmelding_manuell"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arkivertoppdrag",
            options={
                "ordering": ["oppdragsnummer", "enhet_navn"],
                "verbose_name": "Arkivert oppdrag",
                "verbose_name_plural": "Arkiverte oppdrag",
            },
        ),
        migrations.AlterUniqueTogether(
            name="arkivertoppdrag",
            unique_together={("arkiv", "oppdragsnummer", "enhet_navn")},
        ),
    ]
