# Generated by Django 5.2.17 on 2026-09-12 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0013_arkivrad_per_enhet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enhetshendelse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("tatt_av", "Tatt av oppdraget")],
                        max_length=16,
                        verbose_name="Hendelse",
                    ),
                ),
                ("tidspunkt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enhet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="oppdrag.enhet",
                    ),
                ),
                (
                    "oppdrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enhetshendelser",
                        to="oppdrag.oppdrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enhetshendelse",
                "verbose_name_plural": "Enhetshendelser",
                "ordering": ["tidspunkt"],
            },
        ),
    ]
