# Generated by Django 5.2.17 on 2026-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0017_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="oppdrag",
            name="trenger_ressurs_siden",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trenger ny ressurs siden"
            ),
        ),
    ]
