# Generated by Django 5.2.17 on 2026-09-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Skjema, del 1 av 3 (12. sep. 2026): tabellene og den nye FK-en.
    Oversettingen av `Enhet.type` skjer i `0020`, og feltet fjernes i `0021`
    — tre migrasjoner, ikke én med `SET CONSTRAINTS ALL IMMEDIATE`, se
    «Migrasjoner» i CLAUDE.md."""


    dependencies = [
        ("oppdrag", "0018_trenger_ressurs_siden"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enhetstype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Enhetstype"
                    ),
                ),
                (
                    "er_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktive typer tilbys ikke i enhetspanelet, men enheter som har dem beholder dem.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
            ],
            options={
                "verbose_name": "Enhetstype",
                "verbose_name_plural": "Enhetstyper",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="Problemstilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Problemstilling"
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("medisinsk", "Medisinsk (Akutt, Haster, Vanlig)"),
                            ("drift", "Drift"),
                            ("begge", "Begge"),
                        ],
                        default="medisinsk",
                        max_length=12,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "med_antall",
                    models.BooleanField(
                        default=False,
                        help_text="Bilen setter antall pasienter på oppdraget (f.eks. transport).",
                        verbose_name="Bærer antall",
                    ),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
            ],
            options={
                "verbose_name": "Problemstilling",
                "verbose_name_plural": "Problemstillinger",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.AddField(
            model_name="enhet",
            name="enhetstype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enheter",
                to="oppdrag.enhetstype",
                verbose_name="Enhetstype",
            ),
        ),
    ]
