# Generated by Django 5.2.17 on 2026-09-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0021_fjern_enhet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="arkivertoppdrag",
            name="behandlet_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Behandlet på sted"
            ),
        ),
        migrations.AlterField(
            model_name="enhetshendelse",
            name="type",
            field=models.CharField(
                choices=[
                    ("tatt_av", "Tatt av oppdraget"),
                    ("rykket_videre", "Rykket ut på et annet oppdrag"),
                    ("avbrutt", "Avbrøt oppdraget"),
                ],
                max_length=16,
                verbose_name="Hendelse",
            ),
        ),
        migrations.AlterField(
            model_name="oppdrag",
            name="status",
            field=models.CharField(
                choices=[
                    ("venter", "Venter"),
                    ("rykker_ut", "Rykker ut"),
                    ("fremme", "Fremme"),
                    ("avreist", "Avreist"),
                    ("leverer", "Leverer"),
                    ("behandlet", "Behandlet på sted"),
                    ("ledig", "Ledig"),
                ],
                db_index=True,
                default="venter",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="oppdragsenhet",
            name="status",
            field=models.CharField(
                choices=[
                    ("venter", "Venter"),
                    ("rykker_ut", "Rykker ut"),
                    ("fremme", "Fremme"),
                    ("avreist", "Avreist"),
                    ("leverer", "Leverer"),
                    ("behandlet", "Behandlet på sted"),
                    ("ledig", "Ledig"),
                ],
                db_index=True,
                default="venter",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="statusmelding",
            name="status",
            field=models.CharField(
                choices=[
                    ("venter", "Venter"),
                    ("rykker_ut", "Rykker ut"),
                    ("fremme", "Fremme"),
                    ("avreist", "Avreist"),
                    ("leverer", "Leverer"),
                    ("behandlet", "Behandlet på sted"),
                    ("ledig", "Ledig"),
                ],
                max_length=16,
            ),
        ),
    ]
