# Generated by Django 5.2.17 on 2026-09-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0022_behandlet_og_avbrutt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lydvarsel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "hastegrad",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Hastegrad"
                    ),
                ),
                (
                    "forste_sekunder",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Første varsel etter (sekunder)"
                    ),
                ),
                (
                    "gjenta_sekunder",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Gjenta hvert (sekunder)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lydvarsel",
                "verbose_name_plural": "Lydvarsler",
                "ordering": ["hastegrad"],
            },
        ),
    ]
