# Generated by Django 5.2.17 on 2026-09-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0024_seed_lydvarsel"),
    ]

    operations = [
        migrations.AddField(
            model_name="lydvarsel",
            name="aktiv",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
    ]
