# Generated by Django 5.2.17 on 2026-09-16 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_appsetting_backup_hit"),
        ("oppdrag", "0025_lydvarsel_aktiv"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="arkivertoppdrag",
            name="varslet_modus",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                verbose_name="Vaktmodus ved varsling",
            ),
        ),
        migrations.AddField(
            model_name="enhet",
            name="passiv_vakt",
            field=models.BooleanField(
                default=False,
                help_text="Bakvakt: enheten kan varsles, men står ikke klar. Krever at enhetstypen tillater det.",
                verbose_name="Passiv vakt",
            ),
        ),
        migrations.AddField(
            model_name="enhetshendelse",
            name="kvittert_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Kvittert"),
        ),
        migrations.AddField(
            model_name="enhetshendelse",
            name="kvittert_av",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kvittert av",
            ),
        ),
        migrations.AddField(
            model_name="enhetstype",
            name="kan_avvente",
            field=models.BooleanField(
                default=False,
                help_text="Operatøren kan sette enheten til «avventer» når hun sier på nødnett at hun ikke kan ta oppdraget nå.",
                verbose_name="Kan avvente et oppdrag",
            ),
        ),
        migrations.AddField(
            model_name="enhetstype",
            name="kan_passiv_vakt",
            field=models.BooleanField(
                default=False,
                help_text="Bakvakt gjennom hele arrangementet. Enheter av denne typen kan settes aktiv/passiv, og passiv tid dokumenteres.",
                verbose_name="Kan stå i passiv vakt",
            ),
        ),
        migrations.AddField(
            model_name="oppdragsenhet",
            name="varslet_modus",
            field=models.CharField(
                blank=True,
                choices=[("aktiv", "Aktiv vakt"), ("passiv", "Passiv vakt")],
                default="",
                max_length=8,
                verbose_name="Vaktmodus ved varsling",
            ),
        ),
        migrations.AlterField(
            model_name="enhetshendelse",
            name="type",
            field=models.CharField(
                choices=[
                    ("tatt_av", "Tatt av oppdraget"),
                    ("rykket_videre", "Rykket ut på et annet oppdrag"),
                    ("avbrutt", "Avbrøt oppdraget"),
                    ("avventer", "Avventer oppdraget"),
                ],
                max_length=16,
                verbose_name="Hendelse",
            ),
        ),
        migrations.CreateModel(
            name="Vaktmodusperiode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "modus",
                    models.CharField(
                        choices=[("aktiv", "Aktiv vakt"), ("passiv", "Passiv vakt")],
                        max_length=8,
                        verbose_name="Modus",
                    ),
                ),
                (
                    "fra",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fra"
                    ),
                ),
                (
                    "til",
                    models.DateTimeField(blank=True, null=True, verbose_name="Til"),
                ),
                (
                    "enhet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaktmodusperioder",
                        to="oppdrag.enhet",
                        verbose_name="Enhet",
                    ),
                ),
                (
                    "satt_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Satt av",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaktmodusperioder",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaktmodusperiode",
                "verbose_name_plural": "Vaktmodusperioder",
                "ordering": ["fra"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("til__isnull", True)),
                        fields=("enhet", "vakt"),
                        name="en_apen_vaktmodus_per_enhet",
                    )
                ],
            },
        ),
    ]
