# Generated by Django 5.2 on 2026-09-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0004_hendelse"),
        ("oppdrag", "0026_arkivertoppdrag_varslet_modus_enhet_passiv_vakt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oppdrag",
            name="hendelse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oppdrag",
                to="ko.hendelse",
                verbose_name="Hendelse",
            ),
        ),
    ]
