# Generated by Django 5.2.17 on 2026-09-23 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0031_statusmelding_trukket_tilbake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Oppdragsendring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "felt",
                    models.CharField(
                        choices=[
                            ("hastegrad", "Hastegrad"),
                            ("problemstilling", "Problemstilling"),
                            ("lokasjon", "Lokasjon"),
                            ("fritekst", "Oppdragsnotat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fra_verdi", models.CharField(blank=True, default="", max_length=255)),
                ("til_verdi", models.CharField(blank=True, default="", max_length=255)),
                ("automatisk", models.BooleanField(default=False)),
                (
                    "endret_av_navn",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "endret_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oppdragsendringer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oppdrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endringer",
                        to="oppdrag.oppdrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oppdragsendring",
                "verbose_name_plural": "Oppdragsendringer",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
