# Generated by Django 5.2.17 on 2026-09-26 14:00

import core.sortering
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0032_oppdragsendring"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enhet",
            options={
                "ordering": [core.sortering.Norsk("navn")],
                "verbose_name": "Enhet",
                "verbose_name_plural": "Enheter",
            },
        ),
        migrations.AlterModelOptions(
            name="enhetstype",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Enhetstype",
                "verbose_name_plural": "Enhetstyper",
            },
        ),
        migrations.AlterModelOptions(
            name="lokasjon",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Lokasjon",
                "verbose_name_plural": "Lokasjoner",
            },
        ),
        migrations.AlterModelOptions(
            name="problemstilling",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Problemstilling",
                "verbose_name_plural": "Problemstillinger",
            },
        ),
    ]
