# Generated by Django 5.2.17 on 2026-08-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kompetanse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(max_length=120, unique=True, verbose_name="Navn"),
                ),
                (
                    "er_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktive kompetanser skjules i nedtrekkslister, men beholdes på mannskapet som har dem.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(
                        default=100,
                        help_text="Lavere kommer først i lister.",
                        verbose_name="Rekkefølge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kompetanse",
                "verbose_name_plural": "Kompetanser",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="Korps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(max_length=120, unique=True, verbose_name="Navn"),
                ),
                (
                    "kortnavn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vises i trange kolonner, f.eks. «HGSD». Valgfritt.",
                        max_length=20,
                        verbose_name="Kortnavn",
                    ),
                ),
                (
                    "er_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktive korps skjules i nedtrekkslister, men beholdes på mannskapet som allerede tilhører dem.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(
                        default=100,
                        help_text="Lavere kommer først i lister.",
                        verbose_name="Rekkefølge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Korps",
                "verbose_name_plural": "Korps",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="VaktRolle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(max_length=120, unique=True, verbose_name="Navn"),
                ),
                (
                    "er_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktive roller skjules i nedtrekkslister, men beholdes på vaktposter som allerede bruker dem.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(
                        default=100,
                        help_text="Lavere kommer først i lister.",
                        verbose_name="Rekkefølge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaktrolle",
                "verbose_name_plural": "Vaktroller",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="Mannskap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                ("navn", models.CharField(max_length=150, verbose_name="Navn")),
                (
                    "telefon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brukes av KO og vaktleder under vakt. Valgfritt.",
                        max_length=20,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "er_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Pensjonerte mannskaper skjules i lister, men beholdes på historiske vaktposter. Den normale veien ut av registeret.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "notat",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fritekst. Verdiene logges ikke i revisjonsloggen. IKKE skriv helseopplysninger her — kostbehov og allergier skal ikke inn i portalen.",
                        verbose_name="Notat",
                    ),
                ),
                (
                    "kompetanser",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mannskap",
                        to="vaktliste.kompetanse",
                        verbose_name="Kompetanser",
                    ),
                ),
                (
                    "korps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mannskap",
                        to="vaktliste.korps",
                        verbose_name="Korps",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Valgfri kobling til en portalbruker. Fra fase 3 avgjør den hvilket korps kontoen kan redigere. Gir i seg selv ingen tilgang.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mannskap",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Koblet konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mannskap",
                "verbose_name_plural": "Mannskap",
                "ordering": ["korps__rekkefolge", "korps__navn", "navn"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("korps", "navn"), name="unikt_navn_per_korps"
                    )
                ],
            },
        ),
    ]
