# Generated by Django 5.2.17 on 2026-08-29 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_vakt"),
        ("oppdrag", "0008_arkiv"),
        ("vaktliste", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaktliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("planlegging", "Planlegging"), ("drift", "I drift")],
                        db_index=True,
                        default="planlegging",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "satt_i_drift_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Satt i drift"
                    ),
                ),
                (
                    "notat",
                    models.TextField(blank=True, default="", verbose_name="Notat"),
                ),
                (
                    "satt_i_drift_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaktlister_satt_i_drift",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Satt i drift av",
                    ),
                ),
                (
                    "vakt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaktliste",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaktliste",
                "verbose_name_plural": "Vaktlister",
                "ordering": ["-vakt__startet"],
            },
        ),
        migrations.CreateModel(
            name="Ressurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        help_text="Slik den omtales på vakta, f.eks. «Mannskapsbil 1».",
                        max_length=120,
                        verbose_name="Navn",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("samleplass", "Samleplass"),
                            ("mannskapsbil", "Mannskapsbil"),
                            ("ambulanse", "Ambulanse"),
                            ("lag", "Lag"),
                            ("ko", "KO"),
                            ("annet", "Annet"),
                        ],
                        default="annet",
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(
                        default=100,
                        help_text="Lavere kommer først. Styrer fanerekkefølgen.",
                        verbose_name="Rekkefølge",
                    ),
                ),
                (
                    "enhet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kobles for biler og ambulanser, slik at sentralbordet kan vise besetningen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaktliste_ressurser",
                        to="oppdrag.enhet",
                        verbose_name="Enhet i oppdragsmodulen",
                    ),
                ),
                (
                    "korps",
                    models.ForeignKey(
                        blank=True,
                        help_text="Korpset som har fått ressursen. Tom = ureservert, og bemannes da av vaktleder.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reserverte_ressurser",
                        to="vaktliste.korps",
                        verbose_name="Reservert korps",
                    ),
                ),
                (
                    "vaktliste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ressurser",
                        to="vaktliste.vaktliste",
                        verbose_name="Vaktliste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressurs",
                "verbose_name_plural": "Ressurser",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="Vaktpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                ("fra_tid", models.DateTimeField(verbose_name="Fra")),
                ("til_tid", models.DateTimeField(verbose_name="Til")),
                (
                    "mott_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Møtt"),
                ),
                (
                    "av_vakt_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Av vakt"),
                ),
                (
                    "avmeldt_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Personen har meldt fra at hun ikke kommer. Raden blir stående, slik at det synes at plassen ble tom.",
                        null=True,
                        verbose_name="Avmeldt",
                    ),
                ),
                (
                    "merknad",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Merknad"
                    ),
                ),
                (
                    "mannskap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaktposter",
                        to="vaktliste.mannskap",
                        verbose_name="Mannskap",
                    ),
                ),
                (
                    "ressurs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaktposter",
                        to="vaktliste.ressurs",
                        verbose_name="Ressurs",
                    ),
                ),
                (
                    "rolle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaktposter",
                        to="vaktliste.vaktrolle",
                        verbose_name="Rolle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaktpost",
                "verbose_name_plural": "Vaktposter",
                "ordering": ["fra_tid", "mannskap__navn"],
            },
        ),
        migrations.AddConstraint(
            model_name="ressurs",
            constraint=models.UniqueConstraint(
                fields=("vaktliste", "navn"), name="unikt_ressursnavn_per_vaktliste"
            ),
        ),
        migrations.AddIndex(
            model_name="vaktpost",
            index=models.Index(
                fields=["ressurs", "fra_tid"], name="vaktpost_ress_tid_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vaktpost",
            constraint=models.UniqueConstraint(
                fields=("ressurs", "mannskap", "fra_tid"),
                name="unikt_skift_per_person_og_ressurs",
            ),
        ),
    ]
