# Generated by Django 5.2.17 on 2026-08-30 05:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0002_oppsett"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kompetanse",
            options={
                "ordering": [django.db.models.functions.text.Lower("navn")],
                "verbose_name": "Kompetanse",
                "verbose_name_plural": "Kompetanser",
            },
        ),
        migrations.AlterModelOptions(
            name="korps",
            options={
                "ordering": [django.db.models.functions.text.Lower("navn")],
                "verbose_name": "Korps",
                "verbose_name_plural": "Korps",
            },
        ),
        migrations.AlterModelOptions(
            name="mannskap",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("korps__navn"),
                    django.db.models.functions.text.Lower("navn"),
                ],
                "verbose_name": "Mannskap",
                "verbose_name_plural": "Mannskap",
            },
        ),
        migrations.AlterModelOptions(
            name="vaktrolle",
            options={
                "ordering": [django.db.models.functions.text.Lower("navn")],
                "verbose_name": "Vaktrolle",
                "verbose_name_plural": "Vaktroller",
            },
        ),
        migrations.RemoveField(
            model_name="kompetanse",
            name="rekkefolge",
        ),
        migrations.RemoveField(
            model_name="korps",
            name="rekkefolge",
        ),
        migrations.RemoveField(
            model_name="vaktrolle",
            name="rekkefolge",
        ),
        migrations.AlterField(
            model_name="ressurs",
            name="rekkefolge",
            field=models.IntegerField(
                default=100,
                help_text="Styrer fanerekkefølgen. Settes automatisk til opprettelsesrekkefølgen — se services.neste_rekkefolge().",
                verbose_name="Rekkefølge",
            ),
        ),
    ]
