# Generated by Django 5.2.17 on 2026-08-30 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0003_fjern_rekkefolge_fra_verdimengdene"),
    ]

    operations = [
        migrations.AddField(
            model_name="kompetanse",
            name="bygger_paa",
            field=models.ForeignKey(
                blank=True,
                help_text="Kompetansen denne overordner, f.eks. VFØR for AFØR. Har personen begge, vises bare denne.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overordner",
                to="vaktliste.kompetanse",
                verbose_name="Bygger på",
            ),
        ),
    ]
