# Generated by Django 5.2.17 on 2026-08-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0004_kompetansestige"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaktliste",
            name="planlagt_slutt",
            field=models.DateTimeField(
                blank=True,
                help_text="Når vakta er tenkt å være over. Styrer bemanningskurven.",
                null=True,
                verbose_name="Planlagt slutt",
            ),
        ),
        migrations.AlterField(
            model_name="vaktpost",
            name="mannskap",
            field=models.ForeignKey(
                blank=True,
                help_text="Tom = ledig plass som skal fylles.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vaktposter",
                to="vaktliste.mannskap",
                verbose_name="Mannskap",
            ),
        ),
    ]
