# Generated by Django 5.2.17 on 2026-08-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0009_grupper_med_en_enhet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Belastningsgrenser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maks_skift_timer",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Skift over dette merkes i planleggingstallene. Standard 12 timer.",
                        verbose_name="Lengste skift (timer)",
                    ),
                ),
                (
                    "min_hvile_timer",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Mindre hvile enn dette mellom to skift merkes. Standard 8 timer.",
                        verbose_name="Korteste hvile (timer)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Belastningsgrenser",
                "verbose_name_plural": "Belastningsgrenser",
            },
        ),
    ]
