# Generated by Django 5.2.17 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0012_alle_korps"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaktliste",
            name="arkivert_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Arkivert"
            ),
        ),
    ]
