# Generated by Django 5.2.17 on 2026-09-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0014_mannskap_epost"),
    ]

    operations = [
        migrations.AddField(
            model_name="mannskap",
            name="issi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nødnettsterminalens ISSI. Valgfritt.",
                max_length=20,
                verbose_name="ISSI",
            ),
        ),
    ]
