# Generated by Django 5.2.17 on 2026-09-12 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0015_mannskap_issi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Utsending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "sendt_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Sendt av (navn)",
                    ),
                ),
                (
                    "utloest",
                    models.CharField(
                        choices=[("knapp", "Knapp"), ("drift", "Sett i drift")],
                        default="knapp",
                        max_length=10,
                        verbose_name="Utløst av",
                    ),
                ),
                (
                    "mottakere",
                    models.TextField(blank=True, default="", verbose_name="Mottakere"),
                ),
                (
                    "antall_rader",
                    models.PositiveIntegerField(default=0, verbose_name="Antall skift"),
                ),
                ("feil", models.TextField(blank=True, default="", verbose_name="Feil")),
                (
                    "sendt_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sendt av",
                    ),
                ),
                (
                    "vaktliste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utsendinger",
                        to="vaktliste.vaktliste",
                        verbose_name="Vaktliste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utsending",
                "verbose_name_plural": "Utsendinger",
                "ordering": ["-created_at"],
            },
        ),
    ]
