# Generated by Django 5.2.17 on 2026-09-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0016_utsending"),
    ]

    operations = [
        migrations.AddField(
            model_name="utsending",
            name="innhold_sha256",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Innholdssignatur"
            ),
        ),
        migrations.AlterField(
            model_name="utsending",
            name="utloest",
            field=models.CharField(
                choices=[
                    ("knapp", "Knapp"),
                    ("drift", "Sett i drift"),
                    ("intervall", "Intervall"),
                ],
                default="knapp",
                max_length=10,
                verbose_name="Utløst av",
            ),
        ),
    ]
