# Generated by Django 5.2.17 on 2026-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0017_utsending_intervall"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaktliste",
            name="timetak",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Budsjett i timer for hele vakta. Varsler, sperrer ikke.",
                null=True,
                verbose_name="Timetak",
            ),
        ),
    ]
