# Generated by Django 5.2.17 on 2026-09-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0019_rollerekkefolge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vaktpost",
            options={
                "ordering": [
                    "fra_tid",
                    models.OrderBy(models.F("rolle__rekkefolge"), nulls_last=True),
                    models.OrderBy(models.F("mannskap__navn"), nulls_first=True),
                ],
                "verbose_name": "Vaktpost",
                "verbose_name_plural": "Vaktposter",
            },
        ),
    ]
