# Generated by Django 5.2.17 on 2026-09-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0020_vaktpost_sortering"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressurs",
            name="pause_etter_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minutter fra skiftets start til pausen. Tom = ingen regel.",
                null=True,
                verbose_name="Pause etter (min)",
            ),
        ),
        migrations.AddField(
            model_name="ressurs",
            name="pause_forskyv",
            field=models.BooleanField(
                default=True,
                help_text="Lag i samme gruppe med samme skiftstart tar pause etter hverandre, ikke samtidig.",
                verbose_name="Forskyv pausene",
            ),
        ),
        migrations.AddField(
            model_name="ressurs",
            name="pause_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Pauselengde (min)"
            ),
        ),
        migrations.CreateModel(
            name="Pause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                ("fra", models.DateTimeField(verbose_name="Fra")),
                ("til", models.DateTimeField(verbose_name="Til")),
                (
                    "fra_regel",
                    models.BooleanField(
                        default=False, verbose_name="Fra planleggerens regel"
                    ),
                ),
                (
                    "ressurs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauser",
                        to="vaktliste.ressurs",
                        verbose_name="Ressurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pause",
                "verbose_name_plural": "Pauser",
                "ordering": ["fra", "id"],
                "indexes": [
                    models.Index(fields=["ressurs", "fra"], name="pause_ress_fra_idx")
                ],
            },
        ),
    ]
