# Generated by Django 5.2.17 on 2026-09-25 18:49

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0021_pauser"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaktliste",
            name="brannrutine",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Står øverst på brannlista: samleplass og hva som gjøres ved alarm.",
                verbose_name="Brannrutine",
            ),
        ),
        migrations.CreateModel(
            name="Overnattingsrom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                ("navn", models.CharField(max_length=80, verbose_name="Navn")),
                (
                    "plassering",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bygg og etasje — det brannvesenet spør om.",
                        max_length=120,
                        verbose_name="Plassering",
                    ),
                ),
                (
                    "kapasitet",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Høyst så mange skal sove her. Tom = ikke satt. Varsler, sperrer ikke.",
                        null=True,
                        verbose_name="Kapasitet",
                    ),
                ),
                (
                    "merknad",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="F.eks. nødutgang. Om rommet, aldri om en person.",
                        max_length=200,
                        verbose_name="Merknad",
                    ),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
                (
                    "vaktliste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overnattingsrom",
                        to="vaktliste.vaktliste",
                        verbose_name="Vaktliste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overnattingsrom",
                "verbose_name_plural": "Overnattingsrom",
                "ordering": ["rekkefolge", "id"],
            },
        ),
        migrations.CreateModel(
            name="Overnatting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tidspunktet raden ble opprettet.",
                        verbose_name="Opprettet",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tidspunktet raden sist ble endret.",
                        verbose_name="Sist oppdatert",
                    ),
                ),
                (
                    "natt",
                    models.DateField(
                        help_text="Datoen kvelden natta begynner.", verbose_name="Natt"
                    ),
                ),
                (
                    "mannskap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overnattinger",
                        to="vaktliste.mannskap",
                        verbose_name="Mannskap",
                    ),
                ),
                (
                    "rom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overnattinger",
                        to="vaktliste.overnattingsrom",
                        verbose_name="Rom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overnatting",
                "verbose_name_plural": "Overnattinger",
                "ordering": ["natt", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="overnattingsrom",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("navn"),
                models.F("vaktliste"),
                name="overnattingsrom_unikt_navn",
            ),
        ),
        migrations.AddIndex(
            model_name="overnatting",
            index=models.Index(fields=["rom", "natt"], name="overnatting_rom_natt_idx"),
        ),
        migrations.AddConstraint(
            model_name="overnatting",
            constraint=models.UniqueConstraint(
                fields=("mannskap", "natt"), name="overnatting_ett_sted_per_natt"
            ),
        ),
    ]
