# Generated by Django 5.2.17 on 2026-09-26 14:00

import core.sortering
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0022_overnatting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kompetanse",
            options={
                "ordering": [core.sortering.Norsk("navn")],
                "verbose_name": "Kompetanse",
                "verbose_name_plural": "Kompetanser",
            },
        ),
        migrations.AlterModelOptions(
            name="korps",
            options={
                "ordering": [core.sortering.Norsk("navn")],
                "verbose_name": "Korps",
                "verbose_name_plural": "Korps",
            },
        ),
        migrations.AlterModelOptions(
            name="mannskap",
            options={
                "ordering": [
                    core.sortering.Norsk("korps__navn"),
                    core.sortering.Norsk("navn"),
                ],
                "verbose_name": "Mannskap",
                "verbose_name_plural": "Mannskap",
            },
        ),
        migrations.AlterModelOptions(
            name="ressurs",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Ressurs",
                "verbose_name_plural": "Ressurser",
            },
        ),
        migrations.AlterModelOptions(
            name="ressursgruppe",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Ressursgruppe",
                "verbose_name_plural": "Ressursgrupper",
            },
        ),
        migrations.AlterModelOptions(
            name="ressursrolle",
            options={
                "ordering": [
                    "gruppe__rekkefolge",
                    "rekkefolge",
                    core.sortering.Norsk("navn"),
                ],
                "verbose_name": "Ressursrolle",
                "verbose_name_plural": "Ressursroller",
            },
        ),
        migrations.AlterModelOptions(
            name="vaktpost",
            options={
                "ordering": [
                    "fra_tid",
                    models.OrderBy(models.F("rolle__rekkefolge"), nulls_last=True),
                    models.OrderBy(
                        core.sortering.Norsk("mannskap__navn"), nulls_first=True
                    ),
                ],
                "verbose_name": "Vaktpost",
                "verbose_name_plural": "Vaktposter",
            },
        ),
    ]
