# Generated by Django 5.2.17 on 2026-09-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0023_norsk_sortering"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressursgruppe",
            name="registrerer_i_park",
            field=models.BooleanField(
                default=False,
                help_text="Ressursene i gruppa kan velges på parksiden, der lagene registrerer hva de har gjort.",
                verbose_name="Registrerer i /park/",
            ),
        ),
    ]
