# Generated by Django 5.2.17 on 2026-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0025_lag_registrerer_i_park"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ressursgruppe",
            name="registrerer_i_park",
            field=models.BooleanField(
                default=False,
                help_text="Ressursene i gruppa kan velges i lagregistreringen, der lagene registrerer hva de har gjort.",
                verbose_name="Registrerer i /lag/",
            ),
        ),
    ]
