# Generated by Django 5.2.17 on 2026-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0026_ressursgruppe_lagregistrering_tekst"),
    ]

    operations = [
        migrations.AddField(
            model_name="mannskap",
            name="epost_fra_leder",
            field=models.BooleanField(
                default=True, verbose_name="E-posten er lagt inn av en leder"
            ),
        ),
    ]
