# Generated by Django 5.2.17 on 2026-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaktliste", "0027_mannskap_epost_fra_leder"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaktliste",
            name="drift_automatisk",
            field=models.BooleanField(
                db_default=False, default=False, verbose_name="Satt i drift automatisk"
            ),
        ),
    ]
