# Generated by Django 5.2.13 on 2026-05-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_table_n_dc0494_idx',
            old_name='audit_auditlog_table_rec_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_auditlog_created_idx',
        ),
    ]
