# Generated by Django 5.2.14 on 2026-08-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_app_label'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_audit_created_a3c1b8_idx',
        ),
    ]
