# Generated by Django 5.2.17 on 2026-09-17 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0011_appsetting_backup_hit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Logglinje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kilde",
                    models.CharField(
                        choices=[
                            ("operator", "Ført av operatør"),
                            ("system", "Systemhendelse"),
                        ],
                        db_index=True,
                        default="operator",
                        max_length=16,
                        verbose_name="Kilde",
                    ),
                ),
                (
                    "systemkode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=32,
                        verbose_name="Systemkode",
                    ),
                ),
                (
                    "systemdata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Systemdata"
                    ),
                ),
                (
                    "tidspunkt",
                    models.DateTimeField(db_index=True, verbose_name="Tidspunkt"),
                ),
                (
                    "registrert_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Registrert"
                    ),
                ),
                (
                    "tekst",
                    models.TextField(blank=True, default="", verbose_name="Tekst"),
                ),
                (
                    "forfatter_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Ført av (navn)",
                    ),
                ),
                (
                    "forfatter_delt_konto",
                    models.BooleanField(default=False, verbose_name="Delt konto"),
                ),
                (
                    "ansvarsomraade",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Ansvarsområde",
                    ),
                ),
                (
                    "fjernet_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Fjernet"
                    ),
                ),
                (
                    "fjernet_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Fjernet av (navn)",
                    ),
                ),
                (
                    "fjernet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_fjernede_logglinjer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fjernet av",
                    ),
                ),
                (
                    "forfatter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_logglinjer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ført av",
                    ),
                ),
                (
                    "korrigerer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="korrigert_av",
                        to="ko.logglinje",
                        verbose_name="Korrigerer",
                    ),
                ),
                (
                    "rot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kjede",
                        to="ko.logglinje",
                        verbose_name="Første ledd",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ko_logglinjer",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logglinje",
                "verbose_name_plural": "Logglinjer",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["vakt", "id"], name="ko_logg_vakt_id_idx")
                ],
            },
        ),
    ]
