# Generated by Django 5.2 on 2026-09-17 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0001_initial"),
        ("vaktliste", "0020_vaktpost_sortering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressursstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ledig", "Ledig"),
                            ("opptatt", "Opptatt"),
                            ("pause", "Pause"),
                            ("ute_av_drift", "Ute av drift"),
                        ],
                        default="ledig",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("satt_at", models.DateTimeField(verbose_name="Satt")),
                (
                    "satt_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Satt av (navn)",
                    ),
                ),
                (
                    "ressurs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ko_status",
                        to="vaktliste.ressurs",
                        verbose_name="Ressurs",
                    ),
                ),
                (
                    "satt_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_ressursstatuser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Satt av",
                    ),
                ),
            ],
            options={
                "verbose_name": "KO-ført ressursstatus",
                "verbose_name_plural": "KO-førte ressursstatuser",
                "ordering": ["ressurs_id"],
            },
        ),
    ]
