# Generated by Django 5.2 on 2026-09-18 04:40

"""Fjerner `Ressursstatus` igjen — verdimengden var funnet på.

Tabellen kom i `0002` samme dag (17. sep. 2026) med fire KO-førte statuser:
«Ledig», «Opptatt», «Pause», «Ute av drift». `docs/FORSLAG_KO.md` §3.1 sier at
KO skal føre status for dem som ikke stempler selv, men ikke med hvilke ord —
og `/oppdrag/` har aldri hatt «Pause» eller «Ute av drift» (André, 18. sep.
2026). Ordene var mine, ikke portalens.

**Bare sletting, ingen datamigrering.** Tabellen sto på staging i under et
døgn, KO-flata hadde ingen produksjonsbruk i den perioden, og radene bar
ingenting som ikke også står som en systemlinje i loggen — historikken lå
alltid der, ikke her. Se `ko/backup.py`.

Den tredje kilden i §3.1 er utsatt, ikke forkastet: står i `TODO.md`, og
skal bygges når noen har bestemt hva statusene skal hete.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0002_ressursstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ressursstatus",
        ),
    ]
