# Generated by Django 5.2 on 2026-09-18 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_appsetting_backup_hit"),
        ("ko", "0003_fjern_ressursstatus"),
        ("oppdrag", "0026_arkivertoppdrag_varslet_modus_enhet_passiv_vakt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hendelse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hendelsesnummer",
                    models.IntegerField(verbose_name="Hendelsesnummer"),
                ),
                ("tittel", models.CharField(max_length=120, verbose_name="Tittel")),
                (
                    "lokasjon_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Lokasjon (navn)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("apen", "Åpen"), ("lukket", "Lukket")],
                        db_index=True,
                        default="apen",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "versjon",
                    models.PositiveIntegerField(default=1, verbose_name="Versjon"),
                ),
                (
                    "opprettet_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Opprettet"),
                ),
                (
                    "opprettet_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Opprettet av (navn)",
                    ),
                ),
                (
                    "lukket_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lukket"),
                ),
                (
                    "lukket_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Lukket av (navn)",
                    ),
                ),
                (
                    "lokasjon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_hendelser",
                        to="oppdrag.lokasjon",
                        verbose_name="Lokasjon",
                    ),
                ),
                (
                    "lukket_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_hendelser_lukket",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lukket av",
                    ),
                ),
                (
                    "opprettet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_hendelser_opprettet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opprettet av",
                    ),
                ),
                (
                    "opprettet_fra_linje",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hendelser_opprettet_fra",
                        to="ko.logglinje",
                        verbose_name="Opprettet fra linje",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ko_hendelser",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hendelse",
                "verbose_name_plural": "Hendelser",
                "ordering": ["-hendelsesnummer"],
            },
        ),
        migrations.AddField(
            model_name="logglinje",
            name="hendelse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linjer",
                to="ko.hendelse",
                verbose_name="Hendelse",
            ),
        ),
        migrations.AddConstraint(
            model_name="hendelse",
            constraint=models.UniqueConstraint(
                fields=("vakt", "hendelsesnummer"),
                name="unikt_hendelsesnummer_per_vakt",
            ),
        ),
    ]
