# Generated by Django 5.2 on 2026-09-18 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0004_hendelse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logglinje",
            name="uformell",
            field=models.BooleanField(default=False, verbose_name="Uformell (chat)"),
        ),
        migrations.CreateModel(
            name="Ansvarsmerke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "omraade",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Ansvarsområde",
                    ),
                ),
                ("satt_at", models.DateTimeField(auto_now=True, verbose_name="Satt")),
                (
                    "bruker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ko_ansvar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansvarsmerke",
                "verbose_name_plural": "Ansvarsmerker",
            },
        ),
    ]
