# Generated by Django 5.2.17 on 2026-09-18 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0005_chat_og_ansvar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressursbehov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Ressursbehov"
                    ),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
            ],
            options={
                "verbose_name": "Ressursbehov",
                "verbose_name_plural": "Ressursbehov",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.AddField(
            model_name="hendelse",
            name="beskrivelse",
            field=models.TextField(blank=True, default="", verbose_name="Beskrivelse"),
        ),
        migrations.AddField(
            model_name="hendelse",
            name="lagsressurser",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Lagsressurser"
            ),
        ),
        migrations.AddField(
            model_name="hendelse",
            name="melder",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Melder"
            ),
        ),
        migrations.AddField(
            model_name="hendelse",
            name="prioritet",
            field=models.CharField(
                choices=[
                    ("viktig", "Viktig"),
                    ("rod", "Rød"),
                    ("gul", "Gul"),
                    ("gronn", "Grønn"),
                    ("drift", "Drift"),
                ],
                db_index=True,
                default="gronn",
                max_length=8,
                verbose_name="Prioritet",
            ),
        ),
        migrations.AddField(
            model_name="logglinje",
            name="festet_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Festet"
            ),
        ),
        migrations.AddField(
            model_name="logglinje",
            name="festet_av",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ko_festede_logglinjer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Festet av",
            ),
        ),
        migrations.AddField(
            model_name="logglinje",
            name="festet_av_navn",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Festet av (navn)"
            ),
        ),
        migrations.AddField(
            model_name="hendelse",
            name="ressursbehov",
            field=models.ManyToManyField(
                blank=True,
                related_name="hendelser",
                to="ko.ressursbehov",
                verbose_name="Ressursbehov",
            ),
        ),
        migrations.CreateModel(
            name="HendelseDeltaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brukernavn",
                    models.CharField(max_length=150, verbose_name="Brukernavn"),
                ),
                (
                    "fra",
                    models.DateTimeField(auto_now_add=True, verbose_name="Med fra"),
                ),
                (
                    "bruker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_hendelser_deltatt",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruker",
                    ),
                ),
                (
                    "hendelse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deltakere",
                        to="ko.hendelse",
                        verbose_name="Hendelse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hendelsesdeltaker",
                "verbose_name_plural": "Hendelsesdeltakere",
                "ordering": ["fra", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hendelse", "brukernavn"),
                        name="en_deltaker_per_hendelse",
                    )
                ],
            },
        ),
    ]
