# Generated by Django 5.2.17 on 2026-09-18 18:27

from django.db import migrations, models


def seed(apps, schema_editor):
    """De fire som sto i kode (`ANSVARSOMRAADER`) til 18. sep. 2026. Data
    **etter** skjemaet, aldri før: da fylles ingen triggerkø før `ALTER TABLE`
    (CLAUDE.md, «Migrasjoner»)."""
    Ansvarsomraade = apps.get_model('ko', 'Ansvarsomraade')
    for i, navn in enumerate(('samband', 'ressurser', 'logg', 'media')):
        Ansvarsomraade.objects.get_or_create(navn=navn, defaults={'rekkefolge': (i + 1) * 10})


def tom(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0006_hendelseslogg_2x2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ansvarsomraade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Ansvarsområde"
                    ),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
            ],
            options={
                "verbose_name": "Ansvarsområde",
                "verbose_name_plural": "Ansvarsområder",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
            migrations.RunPython(seed, tom),
    ]
