# Generated by Django 5.2.17 on 2026-09-22 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_appsetting_backup_hit"),
        ("ko", "0012_plassering"),
        ("oppdrag", "0031_statusmelding_trukket_tilbake"),
        ("vaktliste", "0020_vaktpost_sortering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tavleplassering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ressurs_navn",
                    models.CharField(max_length=120, verbose_name="Ressurs (navn)"),
                ),
                (
                    "lokasjon_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Lokasjon (navn)",
                    ),
                ),
                ("pause", models.BooleanField(default=False, verbose_name="Pause")),
                (
                    "hendelse_nummer",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Hendelse"
                    ),
                ),
                ("fra", models.DateTimeField(verbose_name="Fra")),
                (
                    "til",
                    models.DateTimeField(blank=True, null=True, verbose_name="Til"),
                ),
                (
                    "av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Satt av (navn)",
                    ),
                ),
                (
                    "av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_tavleplasseringer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Satt av",
                    ),
                ),
                (
                    "lokasjon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_tavleplasseringer",
                        to="oppdrag.lokasjon",
                        verbose_name="Lokasjon",
                    ),
                ),
                (
                    "ressurs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_tavleplasseringer",
                        to="vaktliste.ressurs",
                        verbose_name="Ressurs",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ko_tavleplasseringer",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tavleplassering",
                "verbose_name_plural": "Tavleplasseringer",
                "ordering": ["fra", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("til__isnull", True)),
                        fields=("ressurs",),
                        name="en_aapen_tavleplassering_per_ressurs",
                    )
                ],
            },
        ),
    ]
