# Generated by Django 5.2.17 on 2026-09-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_appsetting_backup_hit"),
        ("ko", "0013_tavleplassering"),
        ("vaktliste", "0020_vaktpost_sortering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanlagtPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ressurs_navn",
                    models.CharField(max_length=120, verbose_name="Ressurs (navn)"),
                ),
                ("fra", models.DateTimeField(verbose_name="Fra")),
                ("til", models.DateTimeField(verbose_name="Til")),
                (
                    "av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Planlagt av (navn)",
                    ),
                ),
                (
                    "av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_planlagte_pauser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Planlagt av",
                    ),
                ),
                (
                    "ressurs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_planlagte_pauser",
                        to="vaktliste.ressurs",
                        verbose_name="Ressurs",
                    ),
                ),
                (
                    "startet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planlagt_pause",
                        to="ko.tavleplassering",
                        verbose_name="Startet som",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ko_planlagte_pauser",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planlagt pause",
                "verbose_name_plural": "Planlagte pauser",
                "ordering": ["fra", "id"],
            },
        ),
    ]
