# Generated by Django 5.2.17 on 2026-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0014_planlagt_pause"),
    ]

    operations = [
        migrations.AddField(
            model_name="tavleplassering",
            name="planlagt_til",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Planlagt til"
            ),
        ),
    ]
