# Generated by Django 5.2.17 on 2026-09-23 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_appsetting_backup_hit"),
        ("ko", "0015_planlagt_slutt"),
        ("oppdrag", "0032_oppdragsendring"),
        ("vaktliste", "0020_vaktpost_sortering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kjennetegn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Kjennetegn"
                    ),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
            ],
            options={
                "verbose_name": "Kjennetegn",
                "verbose_name_plural": "Kjennetegn",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="Konserttype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Konserttype"
                    ),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
            ],
            options={
                "verbose_name": "Konserttype",
                "verbose_name_plural": "Konserttyper",
                "ordering": ["rekkefolge", "navn"],
            },
        ),
        migrations.CreateModel(
            name="Programpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lokasjon_navn",
                    models.CharField(max_length=255, verbose_name="Sted (navn)"),
                ),
                ("navn", models.CharField(max_length=120, verbose_name="Navn")),
                (
                    "konserttype_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Konserttype (navn)",
                    ),
                ),
                (
                    "beredskap",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gronn", "Grønn"),
                            ("gul", "Gul"),
                            ("oransje", "Oransje"),
                            ("rod", "Rød"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Beredskapsnivå",
                    ),
                ),
                ("fra", models.DateTimeField(verbose_name="Fra")),
                ("til", models.DateTimeField(verbose_name="Til")),
                (
                    "publikum",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Forventet publikum"
                    ),
                ),
                (
                    "endret_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sist endret"),
                ),
                (
                    "endret_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Sist endret av (navn)",
                    ),
                ),
                (
                    "endret_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_programposter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sist endret av",
                    ),
                ),
                (
                    "kjennetegn",
                    models.ManyToManyField(
                        blank=True,
                        related_name="poster",
                        to="ko.kjennetegn",
                        verbose_name="Kjennetegn",
                    ),
                ),
                (
                    "konserttype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poster",
                        to="ko.konserttype",
                        verbose_name="Konserttype",
                    ),
                ),
                (
                    "lokasjon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_program",
                        to="oppdrag.lokasjon",
                        verbose_name="Sted",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ko_program",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programpost",
                "verbose_name_plural": "Programposter",
                "ordering": ["fra", "lokasjon_navn", "id"],
            },
        ),
        migrations.AddField(
            model_name="tavleplassering",
            name="folger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plasseringer",
                to="ko.programpost",
                verbose_name="Følger konserten",
            ),
        ),
        migrations.CreateModel(
            name="Programbehov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gruppe_navn",
                    models.CharField(
                        max_length=60, verbose_name="Ressursgruppe (navn)"
                    ),
                ),
                ("antall", models.PositiveSmallIntegerField(verbose_name="Antall")),
                (
                    "gruppe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_behov",
                        to="vaktliste.ressursgruppe",
                        verbose_name="Ressursgruppe",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behov",
                        to="ko.programpost",
                        verbose_name="Programpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Behov",
                "verbose_name_plural": "Behov",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "gruppe"), name="ett_behov_per_gruppe"
                    )
                ],
            },
        ),
    ]
