# Generated by Django 5.2.17 on 2026-09-23 12:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_appsetting_backup_hit"),
        ("ko", "0017_program_forslag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Programendring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_navn",
                    models.CharField(max_length=120, verbose_name="Konsert (navn)"),
                ),
                (
                    "hva",
                    models.CharField(
                        choices=[
                            ("opprettet", "Lagt til"),
                            ("endret", "Endret"),
                            ("slettet", "Slettet"),
                        ],
                        max_length=10,
                        verbose_name="Hva",
                    ),
                ),
                (
                    "detaljer",
                    models.JSONField(blank=True, default=list, verbose_name="Detaljer"),
                ),
                (
                    "tidspunkt",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tidspunkt"
                    ),
                ),
                (
                    "av_navn",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Av (navn)"
                    ),
                ),
                (
                    "av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_programendringer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Av",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endringer",
                        to="ko.programpost",
                        verbose_name="Programpost",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ko_programendringer",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programendring",
                "verbose_name_plural": "Programendringer",
                "ordering": ["tidspunkt", "id"],
            },
        ),
    ]
