# Generated by Django 5.2.17 on 2026-09-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0018_programendring"),
        ("vaktliste", "0021_pauser"),
    ]

    operations = [
        migrations.AddField(
            model_name="planlagtpause",
            name="avlyst",
            field=models.BooleanField(default=False, verbose_name="Tatt bort i drift"),
        ),
        migrations.AddField(
            model_name="planlagtpause",
            name="endret",
            field=models.BooleanField(default=False, verbose_name="Endret i drift"),
        ),
        migrations.AddField(
            model_name="planlagtpause",
            name="fra_vaktliste",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ko_overtatt",
                to="vaktliste.pause",
                verbose_name="Fra vaktlistas pause",
            ),
        ),
    ]
