# Generated by Django 5.2.17 on 2026-09-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0019_pause_fra_vaktliste"),
        ("oppdrag", "0032_oppdragsendring"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="konserttype",
            options={
                "ordering": ["rekkefolge", "navn"],
                "verbose_name": "Artist",
                "verbose_name_plural": "Artister",
            },
        ),
        migrations.AlterModelOptions(
            name="planlagtpause",
            options={
                "ordering": ["fra", "id"],
                "verbose_name": "Planlagt plassering",
                "verbose_name_plural": "Planlagte plasseringer",
            },
        ),
        migrations.AddField(
            model_name="planlagtpause",
            name="lokasjon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ko_planlagte",
                to="oppdrag.lokasjon",
                verbose_name="Lokasjon",
            ),
        ),
        migrations.AddField(
            model_name="planlagtpause",
            name="lokasjon_navn",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Lokasjon (navn)"
            ),
        ),
        migrations.AddField(
            model_name="planlagtpause",
            name="pause",
            field=models.BooleanField(default=True, verbose_name="Pause"),
        ),
        migrations.AlterField(
            model_name="konserttype",
            name="navn",
            field=models.CharField(max_length=60, unique=True, verbose_name="Artist"),
        ),
    ]
