# Generated by Django 5.2.17 on 2026-09-26 14:00

import core.sortering
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0021_artister_uten_typeforslag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ansvarsomraade",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Ansvarsområde",
                "verbose_name_plural": "Ansvarsområder",
            },
        ),
        migrations.AlterModelOptions(
            name="kjennetegn",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Kjennetegn",
                "verbose_name_plural": "Kjennetegn",
            },
        ),
        migrations.AlterModelOptions(
            name="konserttype",
            options={
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "verbose_name": "Artist",
                "verbose_name_plural": "Artister",
            },
        ),
        migrations.AlterModelOptions(
            name="programpost",
            options={
                "ordering": ["fra", core.sortering.Norsk("lokasjon_navn"), "id"],
                "verbose_name": "Programpost",
                "verbose_name_plural": "Programposter",
            },
        ),
    ]
