# Generated by Django 5.2.17 on 2026-09-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ko", "0022_norsk_sortering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HendelseLest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "til_linje",
                    models.BigIntegerField(
                        default=0, verbose_name="Sett til og med linje"
                    ),
                ),
                (
                    "oppdatert_at",
                    models.DateTimeField(auto_now=True, verbose_name="Oppdatert"),
                ),
                (
                    "bruker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ko_hendelser_lest",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruker",
                    ),
                ),
                (
                    "hendelse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesemerker",
                        to="ko.hendelse",
                        verbose_name="Hendelse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesemerke for hendelse",
                "verbose_name_plural": "Lesemerker for hendelser",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hendelse", "bruker"),
                        name="ett_lesemerke_per_bruker_og_hendelse",
                    )
                ],
            },
        ),
    ]
