# Generated by Django 6.0.4 on 2026-04-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_behandler_and_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helsepersonell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Navn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
            ],
            options={
                'verbose_name': 'Helsepersonell',
                'verbose_name_plural': 'Helsepersonell',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='helsepersonell',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Helsepersonell (tekst, utgående)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='helsepersonell_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.helsepersonell', verbose_name='Helsepersonell'),
        ),
    ]
