# Generated by Django 5.1.15 on 2026-05-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_backup_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaktArkiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=255, verbose_name='Tittel')),
                ('arrangement_navn', models.CharField(max_length=255, verbose_name='Arrangementsnavn')),
                ('importert_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Importert')),
                ('antall_pasienter', models.IntegerField(verbose_name='Antall pasienter')),
                ('year_snapshot', models.IntegerField(verbose_name='År (snapshot)')),
                ('notat', models.TextField(blank=True, verbose_name='Notat')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('importert_av', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaktarkiver', to=settings.AUTH_USER_MODEL, verbose_name='Importert av')),
            ],
            options={
                'verbose_name': 'Vaktarkiv',
                'verbose_name_plural': 'Vaktarkiver',
                'ordering': ['-importert_at'],
            },
        ),
        migrations.CreateModel(
            name='ArkivertPasient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasientnummer', models.IntegerField(verbose_name='Pasientnummer')),
                ('problemstilling', models.CharField(blank=True, default='', max_length=255, verbose_name='Problemstilling')),
                ('arsak', models.CharField(blank=True, default='', max_length=255, verbose_name='Årsak')),
                ('transport', models.CharField(blank=True, default='', max_length=255, verbose_name='Transport')),
                ('grovsortering', models.CharField(blank=True, default='', max_length=50, verbose_name='Grovsortering')),
                ('plassering', models.CharField(blank=True, default='', max_length=255, verbose_name='Plassering')),
                ('inntid', models.TextField(blank=True, default='', verbose_name='Inntid')),
                ('pabegynt', models.TextField(blank=True, default='', verbose_name='Påbegynt')),
                ('inn_obspost', models.TextField(blank=True, default='', verbose_name='Inn obspost')),
                ('ut_obspost', models.TextField(blank=True, default='', verbose_name='Ut obspost')),
                ('utskrevet', models.TextField(blank=True, default='', verbose_name='Utskrevet')),
                ('utskrevet_til', models.CharField(blank=True, default='', max_length=255, verbose_name='Utskrevet til')),
                ('behandler_navn', models.CharField(blank=True, default='', max_length=255, verbose_name='Behandler (navn)')),
                ('helsepersonell_navn', models.CharField(blank=True, default='', max_length=255, verbose_name='Helsepersonell (navn)')),
                ('lege', models.CharField(blank=True, default='', max_length=50, verbose_name='Lege')),
                ('medisiner', models.CharField(blank=True, default='', max_length=50, verbose_name='Medisiner')),
                ('journal', models.CharField(blank=True, default='', max_length=50, verbose_name='Journal')),
                ('arkiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasienter', to='patients.vaktarkiv', verbose_name='Arkiv')),
            ],
            options={
                'verbose_name': 'Arkivert pasient',
                'verbose_name_plural': 'Arkiverte pasienter',
                'ordering': ['pasientnummer'],
                'unique_together': {('arkiv', 'pasientnummer')},
            },
        ),
    ]
