# Generated by Django 5.1.15 on 2026-05-12 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_backup_module_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='behandler',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Valgfri kobling til en portalbruker. Hvis satt, kan brukeren filtrere egne pasienter og får varsel ved tildeling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behandler_profil', to=settings.AUTH_USER_MODEL, verbose_name='Koblet bruker'),
        ),
        migrations.AddField(
            model_name='helsepersonell',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Valgfri kobling til en portalbruker. Hvis satt, kan brukeren filtrere egne pasienter og får varsel ved tildeling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helsepersonell_profil', to=settings.AUTH_USER_MODEL, verbose_name='Koblet bruker'),
        ),
    ]
