# Generated by Django 5.2.14 on 2026-05-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_link_behandlere_to_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='helsepersonell',
        ),
    ]
