# Generated by Django 5.2.14 on 2026-08-12 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def frys_importert_av_navn(apps, schema_editor):
    """Fyll ``importert_av_navn`` på arkiver som finnes fra før.

    Kjøres etter at feltet er lagt til, men før FK-en blir nullbar. Uten dette
    ville eksisterende arkiver stå uten navn, og visningen ville falle tilbake
    på «ukjent bruker» så snart kontoen ble slettet.
    """
    VaktArkiv = apps.get_model('patients', 'VaktArkiv')
    for arkiv in VaktArkiv.objects.select_related('importert_av').filter(
        importert_av_navn='',
        importert_av__isnull=False,
    ):
        arkiv.importert_av_navn = arkiv.importert_av.username
        arkiv.save(update_fields=['importert_av_navn'])


def reverser(apps, schema_editor):
    """Ingen handling: feltet fjernes uansett av AddField-reverseringen."""


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_rename_behandler_to_forstehjelper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaktarkiv',
            name='importert_av_navn',
            field=models.CharField(blank=True, default='', help_text='Frosset brukernavn på den som arkiverte vakten. Settes ved arkivering og overlever sletting av brukerkontoen.', max_length=150, verbose_name='Importert av (navn)'),
        ),
        migrations.RunPython(frys_importert_av_navn, reverser),
        migrations.AlterField(
            model_name='vaktarkiv',
            name='importert_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaktarkiver', to=settings.AUTH_USER_MODEL, verbose_name='Importert av'),
        ),
    ]
