# Generated by Django 5.2.14 on 2026-08-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_vaktarkiv_importert_av_navn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaktarkiv',
            name='aggregat',
            field=models.JSONField(blank=True, help_text='Ferdig beregnet statistikk lagret ved kollaps: {"basis": …, "full": …}. Erstatter pasientradene permanent.', null=True, verbose_name='Frosset statistikk'),
        ),
        migrations.AddField(
            model_name='vaktarkiv',
            name='aggregat_sha256',
            field=models.CharField(blank=True, default='', help_text='Sjekksum over det frosne aggregatet. Overtar integritetssjekken etter kollaps, siden feltet «sha256» er beregnet over rader som ikke lenger finnes.', max_length=64, verbose_name='SHA-256 (aggregat)'),
        ),
        migrations.AddField(
            model_name='vaktarkiv',
            name='kollapset_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Tidspunkt da pasientradene ble slettet og erstattet av frosset aggregat. Tomt betyr at radnivået fortsatt finnes.', null=True, verbose_name='Kollapset'),
        ),
    ]
