# Generated by Django 5.2.17 on 2026-08-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_vakt"),
        ("patients", "0013_vaktarkiv_kollaps_aggregat"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="vakt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pasienter",
                to="core.vakt",
                verbose_name="Vakt",
            ),
        ),
        migrations.AddField(
            model_name="vaktarkiv",
            name="vakt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vaktarkiver",
                to="core.vakt",
                verbose_name="Vakt",
            ),
        ),
    ]
