# Generated by Django 5.2.17 on 2026-09-26 14:00

import core.sortering
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0018_appsetting_backup_ut"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forstehjelper",
            options={
                "ordering": ["-is_active", core.sortering.Norsk("name")],
                "verbose_name": "Førstehjelper",
                "verbose_name_plural": "Forstehjelpere",
            },
        ),
        migrations.AlterModelOptions(
            name="helsepersonell",
            options={
                "ordering": ["-is_active", core.sortering.Norsk("name")],
                "verbose_name": "Helsepersonell",
                "verbose_name_plural": "Helsepersonell",
            },
        ),
    ]
