# Generated by Django 5.2.17 on 2026-09-27 21:06

import core.sortering
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0013_modulesettings_backup_enabled_slett_kolonnen"),
        ("oppdrag", "0033_norsk_sortering"),
        ("vaktliste", "0024_ressursgruppe_registrerer_i_park"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problemstilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(max_length=64, unique=True, verbose_name="Navn"),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Problemstilling",
                "verbose_name_plural": "Problemstillinger",
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Utfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(max_length=64, unique=True, verbose_name="Navn"),
                ),
                (
                    "rekkefolge",
                    models.IntegerField(default=100, verbose_name="Rekkefølge"),
                ),
                ("er_aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Utfall",
                "verbose_name_plural": "Utfall",
                "ordering": ["rekkefolge", core.sortering.Norsk("navn")],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parklenke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        help_text="Hvor lenken ligger, f.eks. «Tiltakskort Bliksund».",
                        max_length=120,
                        verbose_name="Navn",
                    ),
                ),
                (
                    "hemmelighet_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Hash av tokenet"
                    ),
                ),
                ("aapen_fra", models.DateTimeField(verbose_name="Åpen fra")),
                ("aapen_til", models.DateTimeField(verbose_name="Åpen til")),
                (
                    "opprettet_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Opprettet"),
                ),
                (
                    "opprettet_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Opprettet av (navn)",
                    ),
                ),
                (
                    "fjernet_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fjernet"),
                ),
                (
                    "fjernet_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Fjernet av (navn)",
                    ),
                ),
                (
                    "sist_brukt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sist brukt"
                    ),
                ),
                (
                    "fjernet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fjernet av",
                    ),
                ),
                (
                    "opprettet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opprettet av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parklenke",
                "verbose_name_plural": "Parklenker",
                "ordering": ["-opprettet_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Registrering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ressurs_navn",
                    models.CharField(max_length=120, verbose_name="Lag (navn)"),
                ),
                (
                    "problemstilling",
                    models.CharField(max_length=64, verbose_name="Problemstilling"),
                ),
                (
                    "antall",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Antall"),
                ),
                ("utfall", models.CharField(max_length=64, verbose_name="Utfall")),
                (
                    "lokasjon_navn",
                    models.CharField(max_length=120, verbose_name="Sted (navn)"),
                ),
                (
                    "registrert_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Registrert"),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=36, verbose_name="Idempotensnøkkel"),
                ),
                (
                    "forhandsvalg_kilde",
                    models.CharField(
                        choices=[
                            ("ko", "KO-tavla"),
                            ("registrering", "Lagets siste registrering"),
                            ("telefon", "Telefonens siste valg"),
                            ("ingen", "Ingen"),
                        ],
                        default="ingen",
                        max_length=16,
                        verbose_name="Forhåndsvalg fra",
                    ),
                ),
                (
                    "forhandsvalg_endret",
                    models.BooleanField(
                        default=False, verbose_name="Forhåndsvalget endret"
                    ),
                ),
                (
                    "slettet_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Slettet"),
                ),
                (
                    "slettet_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Slettet av (navn)",
                    ),
                ),
                (
                    "slettet_grunn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Grunn til sletting",
                    ),
                ),
                (
                    "lenke",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registreringer",
                        to="park.parklenke",
                        verbose_name="Lenke",
                    ),
                ),
                (
                    "lokasjon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="park_registreringer",
                        to="oppdrag.lokasjon",
                        verbose_name="Sted",
                    ),
                ),
                (
                    "ressurs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="park_registreringer",
                        to="vaktliste.ressurs",
                        verbose_name="Lag",
                    ),
                ),
                (
                    "slettet_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Slettet av",
                    ),
                ),
                (
                    "vakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="park_registreringer",
                        to="core.vakt",
                        verbose_name="Vakt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registrering",
                "verbose_name_plural": "Registreringer",
                "ordering": ["-registrert_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="parklenke",
            constraint=models.CheckConstraint(
                condition=models.Q(("aapen_til__gt", models.F("aapen_fra"))),
                name="parklenke_til_etter_fra",
            ),
        ),
        migrations.AddIndex(
            model_name="registrering",
            index=models.Index(
                fields=["vakt", "ressurs", "-registrert_at"],
                name="park_reg_vakt_ressurs",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrering",
            constraint=models.UniqueConstraint(
                fields=("lenke", "idempotency_key"),
                name="park_en_registrering_per_nokkel",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrering",
            constraint=models.CheckConstraint(
                condition=models.Q(("antall__gte", 1)), name="park_antall_minst_en"
            ),
        ),
    ]
