# Generated by Django 5.2.17 on 2026-09-28 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oppdrag", "0033_norsk_sortering"),
        ("park", "0002_startverdier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkjultSted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skjult_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skjult"),
                ),
                (
                    "skjult_av_navn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Skjult av (navn)",
                    ),
                ),
                (
                    "lokasjon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="park_skjult",
                        to="oppdrag.lokasjon",
                        verbose_name="Sted",
                    ),
                ),
                (
                    "skjult_av",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Skjult av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skjult sted",
                "verbose_name_plural": "Skjulte steder",
            },
        ),
    ]
